safe: true
markdown: kramdown
pygments: true
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 100
default_lang: en
default_body_class: list

author:
    name: "Дмитрий Дудин @nedudi"
    url:  http://twitter.com/nedudi
    company:
        name: "via @html5by"
        url:  http://html5.by

fork_url: https://github.com/shower/shower
progress: false
line_numbers: false
